# Generated by Django 6.0.4 on 2026-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagement", "0002_alter_receipt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
